### PR TITLE
Plex Docker Switch / mergerfs command update / rclone env add

### PR DESCRIPTION
**Pull request by doob187**
some updates :

Plex Docker switch from pms/docker to LSIO/plex ( more stable and better perfomance )
Plex Docker Hardware transcode added ( over yaml )
mergerfs command some add for faster reading
rclone  enviroments added ( VFS Settings )
pyouroboros/ouroboros added ( replace in the next time watchtower / its much better and can do more for you )

kind regards

### CODE REVIEW

**Comment by TechPerplexed** [comment]
Thank you so much, @doob187 - just love it when Gooby participants contribute code 😄 
Please give @bdschuster and me a few days to review/test and then hopefully merge your pull request 😆

**Comment by doob187** [comment]
i edit some of the install parts for mergerfs . to use the latest OS version 
i fixed one line in install-app part double [[  #sorry  for this ..

kind regards

**Comment by TechPerplexed** [comment]
No worries, it might be a few days before we will be able to review your code... hang tight :)

**Comment by doob187** [comment]
well, then I can deal with it a little more and possibly change a few things. so far I've only noticed the few lines


but i ask myself why you don't use ansible for the docker install and rclone as well as mergerfs, that would be a lot easier and would need less bash lines

**Comment by TechPerplexed** [comment]
Ok, first of all, I can't promise all of your changes and updates will make it into Gooby... we want to make 100% certain that changing one thing doesn't break something else. Right now it's as minimalistic and uniform as possible, which ensures everything is working tightly together.

That brings me to why I chose not to use a shell such as Ansible, although that is a great tool in itself, it would actually add a layer of complexity rather than simplifying matters... plus it would mean that users (or potential code contributors) would have to learn yet another package.

Of course the project is open source, so feel absolutely free to tinker with it as much as you like :) I just can't promise that your changes will make it into the final product... but that definitely doesn't mean that we aren't grateful for your contributions!!

**Comment by TechPerplexed** [comment]
Once again we'd like to thank you so much for contributing code. However, @bdschuster and I have decided not to merge the pull request.

There are a number of reasons and I'll try to list them all for full transparency :)

Plex:

First, you have edited the Plex yaml files to open a large number of ports. This is not only not needed, but could potentially jeopardize the security of the server. It may also interfere with CloudFlare if that is used.

Then, what is your reason for choosing a new repository for Plex (switching to Linuxserver instead of Plex’s own image)? Not arguing against Linuxserver because we use them for practically everything else, but again, if you’re going to NOT use the actual “official” channel, some explanation is necessary.

The hardware version looks very interesting, but at this point, we feel it goes outside the realm of Gooby, especially since Plex keeps changing things around. For example, sometime last year, Plex removed the hardware transcription driver from their Docker so you need to “inject” that later. But this may change again, so we feel it might be better for knowledgable people such as yourself to implement this on an individual basis. Or, alternatively, use your fork :)

Rclone:

Right now, anyone can edit their Rclone service file in any way they see fit, or in whichever way is suitable for their hardware. This is the reason why we chose to keep the configuration file as barebones as possible. By hard coding several variables in the variable file as you have done, we feel that takes away from the freedom of the user. It's a neat idea, but would only work if everyone had the same configuration.

User agent:

I'm not clear what this script accomplishes. You refer to a non existent directory (e.g. uagent=$(cat /var/plexguide/uagent)) which I believe belongs to another project altogether.

Watchtower vs Ouroboros:

Ouroboros seems like an interesting package and we'd definitely consider adding that to the list of applications, but I don't see where it replaces Watchtower. The author admits it doesn’t have as many features as Watchtower and that the main reason he wrote Ouroboros was because Watchtower was written in Go and he wanted to do it in Python. That’s great for the developer but how does that help us? I couldn’t find anything saying that it was faster, more secure, more reliable, etc. Still, thanks very much for mentioning it, I'll definitely consider adding it for self installation at some point :)

Conclusion:

I think it's important to keep in mind what Gooby is meant for. We built it, in order of importance as: 1) a tool to use for ourselves first and foremost; 2) something easy that just about anyone else can deploy; 3) something easy to tweak for the advanced users. Throughout, we kept in mind our ultimate goal which is to provide a near-turnkey setup (for new users or someone restoring/moving to a new VPS).

For full transparency and simplicity we really want to avoid potential weaknesses, such as divergent code development with inconsistent variables, leftover unused code, and things like open ports everywhere. While we welcome outside development and recommendations (and have implemented requests and code from others in the past) we’re also not trying to include everything that has a Docker container or niche unrelated projects.

It was actually a bit hard to find what changes you made since it seems that each file in the repository was somehow altered, so I may have missed a few. However based on the above, at this point we decided not to implement your changes just yet... but as I said feel free to fork and adapt as you wish - that way people have more choices :)

Thanks so much for your contribution though, we really appreciate your time and efforts!

**Comment by doob187** [comment]
all good no problem.  
maybe it's just the impetus in relation to MergerFs and docker install because fixe xenial.deb is used for all OS in the mergerfs  installer , same is the 2.28 is older as the available  version , and it will load always the latest version    do you dint need to edit the files monthly  or weekly , ya I know debian and ubuntu are mostly the same but not in the OS levels, the same also applies to the docker install, gnpug2 is need debian10 and don't needed for ubuntu, for example,

 you can pick things up that you would like,

The PMS docker is switched a long time to LSIO  because the update politic  is each weekly Saturday  09:00 EU TimeZone, 

Inside the Docker is a healthy  checker and automatically  update if you stop the docker , stop start and the update is installed , safely and cleaner  for patches and also is the HETranscode added.  Only what is needed to bind the /dev/dri in the  docker ..  see plex_hwdecode.yaml  , the patched for the deploy I added also. If dev/dri  accessible  the deploy and patch docker..

The rclone  env  you can remove , okay some .lowlevel  user will not edit and customize  they version, standard.0 install works.

Some.parts you can remove skip or leave   but the docker and the mergerfs part I wouldn't  skip , 

fyi  I dont use it   I hel3pd a.froed with the Gobby installed Version ( debian 10 install ). And found the docker is not installed over you script and find the failed part or missing part . As next is see the older version  from mergerfs  and the not os specific deb  .. he used not a VPS and I add him the VFS and HwTranscode inside the docker .. 

Then I made the PR here .. 

I hope it explains  a little bit more 

Sorry german member and translat on the fly

**Comment by TechPerplexed** [comment]
Thanks so much for your explanations - that makes sense :) I will cherry pick through your suggestions and see how the Docker installation can be enhanced. You are actually the second person to mention that it doesn't install on the latest version of Debian, so definitely something to address!

As for MergerFS, actually we chose to pick a certain version on purpose, because in the past some releases were very buggy and others were stable, so we wanted a little more control over the version that was installed. But if they have improved to the point of always being stable, that is certainly a consideration 😄 

Thanks again for your code contribution, I'll keep everything in consideration for sure!

**Comment by TechPerplexed** [comment]
Ok, I have added two test branches for two separate things:

1) Docker installation - to test whether this works with the newer versions of Debian and doesn't break stuff on older installations (or Ubuntu)
2) Plex hardware - this will definitely need some testing, because we only want this to work on servers that support hardware encoding... and not break things on servers that won't support it. 

It'll be a while before testing is done, but at least now we have some progress. Thanks again :)

**Comment by doob187** [comment]
For MergerFs since 2.25 the OS-specific version has become very stable, for some OS levels other packages have been migrated in the deb or other lines of code, so I would switch to an OS-specific installation instead of fixed deb, which in turn also improves the stability of the system  come, I am personally pleased that I was able to provide a few ideas,

**Pull request closed without merging**
